receivers:
  zipkin: # port 9411

exporters:
  zipkin:
    endpoint: "http://localhost:9999/api/v2/spans"

  file:
    path: ./logs/trace.json

service:
  # extensions: [health_check,pprof,zpages]
  pipelines:
    traces:
      receivers: [zipkin]
      processors: []
      exporters: [zipkin, file]
